### ISSUE TITLE
alignment of .account

### ISSUE THREAD

**Issue by cravxx** [DinosParkour/discord-theme#2]
I had this issue when I first applied the theme
![account](https://cloud.githubusercontent.com/assets/8608042/14752199/794c663c-0893-11e6-97fa-6d30fe10bbc2.png)
the source appears to be the .account rules, specifically `
    margin-left: 15px;`
fixed it by going to custom css and putting `.account {
    margin-left: 0px !important;
}`

**Comment by din0s** [comment]
The alignment on my display seems to be fine with the original margin-left.
Do you happen to have any other code in custom-css that could be modifying it?

**Comment by cravxx** [comment]
No, I don't. Perhaps I'll reinstall BetterDiscord and see what happens. As it is now though, it does work for me. It's pretty nice as well.
Edit: Still happens after a reinstall.

**Comment by din0s** [comment]
Which operating system are you running?

**Comment by cravxx** [comment]
Windows 7, screen resolution is 1280x800

**Comment by Fuechschen** [comment]
I've got the same issue on a 1080p monitor on Windows 10

**Comment by din0s** [comment]
@Fuechschen Stable build? PTB?

**Comment by Fuechschen** [comment]
both

**Comment by din0s** [comment]
[This should now be fixed as of v5.11](https://github.com/DinosParkour/discord-theme/commit/1eccc4e6f757b106bf45453d0cf5d51ab06c4603) :smile:

**Comment by Fuechschen** [comment]
Just updated to 5.11, still having the issue on both Discord versions (PTB and stable)

**Comment by din0s** [comment]
Alright alright, it **has to be fixed** in `.12`, blaming long usernames for this issue.
Huge props to Hammock#6027 for identifying the root of this bug :+1:
